default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: test_mutter_development

test:
  <<: *default
  database: test_mutter_test

production:
  <<: *default
  database: test_mutter_production
  username: test_mutter
  password: <%= ENV['TEST_MUTTER_DATABASE_PASSWORD'] %>
